# fly.toml app configuration file generated for rowan-portfolio-api on 2026-04-16T23:28:03-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rowan-portfolio-api'
primary_region = 'ord'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
