/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Veksell (https://sketchfab.com/Veksell)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cat-and-books-e460f285564f44e39a045ece018a446f
Title: Cat and books
*/

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

import { Mesh, MeshPhysicalMaterial } from 'three'

const catshelf = 'https://57zrb2kcas.ufs.sh/f/LHwfoeNVr61i1M7sXq0NaX5s7P2ClbYRvo9kzFAwHBuZ6mV4';

type GLTFResult = GLTF & {
  nodes: {
    shelf_Material002_0: Mesh
    scarf2_Material001_0: Mesh
    scarf1_Material001_0: Mesh
    cat_Material001_0: Mesh
    book1_Material003_0: Mesh
    book2_Material003_0: Mesh
    book3_Material003_0: Mesh
    steam_steam_0: Mesh
    cup_Material002_0: Mesh
    Cube004_Material002_0: Mesh
  }
  materials: {
    ['Material.002']: MeshPhysicalMaterial
    ['Material.001']: MeshPhysicalMaterial
    ['Material.003']: MeshPhysicalMaterial
    steam: MeshPhysicalMaterial
  }
}

export function CatBookShelf(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(catshelf) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="e1d45678d51744c7a7c6cc031964c5affbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}>
            <group name="RootNode">
              <group
                name="shelf"
                position={[0, 0, -34.068]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[100, 74.473, 100]}>
                <mesh
                  name="shelf_Material002_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.shelf_Material002_0.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group
                name="Light"
                position={[-456.223, 1064.339, 74.959]}
                rotation={[1.89, 0.881, -2.045]}
                scale={100}>
                <group name="Object_6" rotation={[Math.PI / 2, 0, 0]}>
                  <group name="Object_7" />
                </group>
              </group>
              <group
                name="Camera"
                position={[-1108.209, 304.393, -227.016]}
                rotation={[0, -0.151, -0.083]}
                scale={100}>
                <group name="Object_9" />
              </group>
              <group
                name="Area"
                position={[-682.339, 645.713, 0]}
                rotation={[0, 0, 0.877]}
                scale={100}>
                <group name="Object_11" rotation={[Math.PI / 2, 0, 0]}>
                  <group name="Object_12" />
                </group>
              </group>
              <group name="Point" position={[-781.706, 253.749, -58.635]} scale={100}>
                <group name="Object_14" rotation={[Math.PI / 2, 0, 0]}>
                  <group name="Object_15" />
                </group>
              </group>
              <group
                name="scarf2"
                position={[-80.375, 112.635, -22.87]}
                rotation={[1.68, 0.604, -0.31]}
                scale={30.46}>
                <mesh
                  name="scarf2_Material001_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.scarf2_Material001_0.geometry}
                  material={materials['Material.001']}
                />
              </group>
              <group
                name="scarf1"
                position={[-6.508, 161.886, -3.016]}
                rotation={[-1.662, 0, 0]}
                scale={100}>
                <mesh
                  name="scarf1_Material001_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.scarf1_Material001_0.geometry}
                  material={materials['Material.001']}
                />
              </group>
              <group
                name="cat"
                position={[0, 241.108, -59.761]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}>
                <mesh
                  name="cat_Material001_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.cat_Material001_0.geometry}
                  material={materials['Material.001']}
                />
              </group>
              <group
                name="book1"
                position={[138.446, 226.626, -273.852]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}>
                <mesh
                  name="book1_Material003_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.book1_Material003_0.geometry}
                  material={materials['Material.003']}
                />
              </group>
              <group
                name="book2"
                position={[204.727, 164.273, -189.406]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[100, 100, 110.147]}>
                <mesh
                  name="book2_Material003_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.book2_Material003_0.geometry}
                  material={materials['Material.003']}
                />
              </group>
              <group
                name="book3"
                position={[138.446, 201.994, -342.101]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[87.183, 47.138, 85.699]}>
                <mesh
                  name="book3_Material003_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.book3_Material003_0.geometry}
                  material={materials['Material.003']}
                />
              </group>
              <group
                name="steam"
                position={[58.955, 281.177, 135.705]}
                rotation={[0, -Math.PI / 2, 0]}
                scale={72.834}>
                <mesh
                  name="steam_steam_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.steam_steam_0.geometry}
                  material={materials.steam}
                />
              </group>
              <group
                name="cup"
                position={[58.955, 132.682, 140.038]}
                rotation={[-Math.PI / 2, 0, 2.82]}
                scale={120.934}>
                <mesh
                  name="cup_Material002_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.cup_Material002_0.geometry}
                  material={materials['Material.002']}
                />
                <group name="Cube004" position={[0, 1.565, -1.139]} scale={0.681}>
                  <mesh
                    name="Cube004_Material002_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube004_Material002_0.geometry}
                    material={materials['Material.002']}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(catshelf)
