/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Kigha (https://sketchfab.com/Kigha)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cute-mocha-cat-3-4b8158f94d9843e89ff1230a7c5107ca
Title: Cute Mocha Cat :3
*/



import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import catCapachinno from "../public/models/catCappuccino.glb"


export function CatCapachinno(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(catCapachinno)
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Mochafbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode">
              <group name="Cup" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="Cup_Glass_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Cup_Glass_0.geometry}
                  material={materials.Glass}
                />
              </group>
              <group name="Liquid" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="Liquid_Full_Cat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Liquid_Full_Cat_0.geometry}
                  material={materials.Full_Cat}
                />
              </group>
              <group
                name="Face"
                position={[0, 0.099, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}>
                <mesh
                  name="Face_Full_Cat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Face_Full_Cat_0.geometry}
                  material={materials.Full_Cat}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(catCapachinno)
