/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AK STUDIO (https://sketchfab.com/inven2000)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coffee-cup-992750b0df674378989fa915b0688ce1
Title: Coffee Cup
*/

import * as THREE from 'three'
import React, { useRef, useState, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import gsap from 'gsap';
import { useGSAP } from '@gsap/react';

const cup = 'https://57zrb2kcas.ufs.sh/f/LHwfoeNVr61iSDgOfNCxWMgwi4haH17qIATON6Q5E2myPSJR';

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial: THREE.Mesh
  }
  materials: {
    DefaultMaterial: THREE.MeshStandardMaterial
  }
}

export function CoffeeCup(props: JSX.IntrinsicElements['group']) {
  const cupRef = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF(cup) as GLTFResult;

  // Floating animation
  useGSAP(() => {
    if (cupRef.current) {
      gsap.to(cupRef.current.position, {
        y: cupRef.current.position.y + 0.2,
        duration: 2,
        repeat: -1,
        yoyo: true,
        ease: "sine.inOut"
      });

      // Gentle rotation
      gsap.to(cupRef.current.rotation, {
        y: Math.PI * 0.1,
        duration: 3,
        repeat: -1,
        yoyo: true,
        ease: "sine.inOut"
      });
    }
  }, []);

  // Hover animation
  const handlePointerOver = () => {
    if (cupRef.current) {
      gsap.to(cupRef.current.scale, {
        x: 1.2,
        y: 1.2,
        z: 1.2,
        duration: 0.3,
        ease: "power2.out"
      });
    }
  };

  const handlePointerOut = () => {
    if (cupRef.current) {
      gsap.to(cupRef.current.scale, {
        x: 1,
        y: 1,
        z: 1,
        duration: 0.3,
        ease: "power2.out"
      });
    }
  };

  return (
    <group 
      {...props} 
      dispose={null} 
      ref={cupRef}
      onPointerOver={handlePointerOver}
      onPointerOut={handlePointerOut}
    >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.099}>
          <group name="Collada_visual_scene_group" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Coffee_Cup">
              <mesh
                name="defaultMaterial"
                castShadow
                receiveShadow
                geometry={nodes.defaultMaterial.geometry}
                material={materials.DefaultMaterial}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(cup)
