/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: LowPolyBoy (https://sketchfab.com/lowPolyBoy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-isometric-cafe-a945f20219c44e94a77cf76929368470
Title: (FREE) Isometric Cafe
*/

import * as THREE from 'three';
import React, { useRef, useState, useEffect } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';


const MODEL_URL = 'https://57zrb2kcas.ufs.sh/f/LHwfoeNVr61imUAX0Y5L7C2KUPRWxSabGDeygQvIZ1OjBH6q';

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_9: THREE.Mesh
    Object_11: THREE.Mesh
    Object_13: THREE.Mesh
    Object_15: THREE.Mesh
    Object_17: THREE.Mesh
    Object_19: THREE.Mesh
    Object_21: THREE.Mesh
    Object_23: THREE.Mesh
    Object_25: THREE.Mesh
    Object_27: THREE.Mesh
    Object_29: THREE.Mesh
    Object_30: THREE.Mesh
    Object_31: THREE.Mesh
    Object_33: THREE.Mesh
    Object_35: THREE.Mesh
    Object_37: THREE.Mesh
    Object_39: THREE.Mesh
    Object_41: THREE.Mesh
    Object_43: THREE.Mesh
    Object_45: THREE.Mesh
    Object_47: THREE.Mesh
    Object_49: THREE.Mesh
    Object_51: THREE.Mesh
    Object_53: THREE.Mesh
    Object_55: THREE.Mesh
    Object_57: THREE.Mesh
    Object_59: THREE.Mesh
    Object_61: THREE.Mesh
    Object_63: THREE.Mesh
    Object_65: THREE.Mesh
    Object_67: THREE.Mesh
    Object_69: THREE.Mesh
    Object_71: THREE.Mesh
    Object_73: THREE.Mesh
    Object_75: THREE.Mesh
    Object_77: THREE.Mesh
    Object_79: THREE.Mesh
    Object_81: THREE.Mesh
    Object_83: THREE.Mesh
    Object_85: THREE.Mesh
    Object_87: THREE.Mesh
    Object_89: THREE.Mesh
    Object_91: THREE.Mesh
    Object_93: THREE.Mesh
    Object_95: THREE.Mesh
    Object_97: THREE.Mesh
    Object_99: THREE.Mesh
    Object_101: THREE.Mesh
    Object_103: THREE.Mesh
    Object_105: THREE.Mesh
    Object_107: THREE.Mesh
    Object_109: THREE.Mesh
    Object_111: THREE.Mesh
    Object_113: THREE.Mesh
    Object_115: THREE.Mesh
    Object_117: THREE.Mesh
    Object_119: THREE.Mesh
    Object_121: THREE.Mesh
    Object_123: THREE.Mesh
    Object_125: THREE.Mesh
    Object_127: THREE.Mesh
    Object_129: THREE.Mesh
    Object_131: THREE.Mesh
    Object_133: THREE.Mesh
    Object_135: THREE.Mesh
    Object_137: THREE.Mesh
    Object_139: THREE.Mesh
    Object_141: THREE.Mesh
    Object_143: THREE.Mesh
    Object_145: THREE.Mesh
    Object_147: THREE.Mesh
    Object_149: THREE.Mesh
    Object_151: THREE.Mesh
    Object_153: THREE.Mesh
    Object_155: THREE.Mesh
    Object_157: THREE.Mesh
    Object_159: THREE.Mesh
    Object_161: THREE.Mesh
    Object_163: THREE.Mesh
    Object_165: THREE.Mesh
    Object_167: THREE.Mesh
    Object_169: THREE.Mesh
    Object_171: THREE.Mesh
    Object_173: THREE.Mesh
    Object_175: THREE.Mesh
    Object_177: THREE.Mesh
    Object_179: THREE.Mesh
    Object_181: THREE.Mesh
    Object_183: THREE.Mesh
    Object_185: THREE.Mesh
    Object_187: THREE.Mesh
    Object_189: THREE.Mesh
    Object_191: THREE.Mesh
    Object_193: THREE.Mesh
    Object_195: THREE.Mesh
    Object_197: THREE.Mesh
    Object_199: THREE.Mesh
    Object_201: THREE.Mesh
    Object_203: THREE.Mesh
    Object_205: THREE.Mesh
    Object_207: THREE.Mesh
    Object_209: THREE.Mesh
    Object_210: THREE.Mesh
    Object_212: THREE.Mesh
    Object_214: THREE.Mesh
    Object_216: THREE.Mesh
    Object_218: THREE.Mesh
    Object_220: THREE.Mesh
    Object_222: THREE.Mesh
    Object_224: THREE.Mesh
    Object_226: THREE.Mesh
    Object_227: THREE.Mesh
    Object_229: THREE.Mesh
    Object_231: THREE.Mesh
    Object_233: THREE.Mesh
    Object_235: THREE.Mesh
    Object_237: THREE.Mesh
    Object_239: THREE.Mesh
    Object_241: THREE.Mesh
    Object_243: THREE.Mesh
    Object_245: THREE.Mesh
    Object_247: THREE.Mesh
    Object_249: THREE.Mesh
    Object_251: THREE.Mesh
    Object_252: THREE.Mesh
    Object_254: THREE.Mesh
    Object_255: THREE.Mesh
    Object_257: THREE.Mesh
    Object_259: THREE.Mesh
    Object_261: THREE.Mesh
    Object_263: THREE.Mesh
    Object_265: THREE.Mesh
    Object_267: THREE.Mesh
    Object_269: THREE.Mesh
    Object_270: THREE.Mesh
    Object_272: THREE.Mesh
    Object_274: THREE.Mesh
    Object_276: THREE.Mesh
    Object_278: THREE.Mesh
    Object_280: THREE.Mesh
    Object_282: THREE.Mesh
    Object_284: THREE.Mesh
    Object_285: THREE.Mesh
    Object_287: THREE.Mesh
    Object_289: THREE.Mesh
    Object_291: THREE.Mesh
    Object_293: THREE.Mesh
    Object_295: THREE.Mesh
    Object_297: THREE.Mesh
    Object_299: THREE.Mesh
    Object_300: THREE.Mesh
    Object_302: THREE.Mesh
    Object_304: THREE.Mesh
    Object_306: THREE.Mesh
    Object_308: THREE.Mesh
    Object_310: THREE.Mesh
    Object_311: THREE.Mesh
    Object_313: THREE.Mesh
    Object_315: THREE.Mesh
    Object_317: THREE.Mesh
    Object_319: THREE.Mesh
    Object_321: THREE.Mesh
    Object_323: THREE.Mesh
    Object_325: THREE.Mesh
    Object_326: THREE.Mesh
    Object_328: THREE.Mesh
    Object_330: THREE.Mesh
    Object_332: THREE.Mesh
    Object_334: THREE.Mesh
    Object_336: THREE.Mesh
    Object_337: THREE.Mesh
    Object_339: THREE.Mesh
    Object_341: THREE.Mesh
    Object_343: THREE.Mesh
    Object_345: THREE.Mesh
    Object_347: THREE.Mesh
    Object_349: THREE.Mesh
    Object_351: THREE.Mesh
    Object_352: THREE.Mesh
    Object_354: THREE.Mesh
    Object_356: THREE.Mesh
    Object_358: THREE.Mesh
    Object_360: THREE.Mesh
    Object_362: THREE.Mesh
    Object_364: THREE.Mesh
    Object_366: THREE.Mesh
    Object_367: THREE.Mesh
    Object_369: THREE.Mesh
    Object_371: THREE.Mesh
    Object_373: THREE.Mesh
    Object_375: THREE.Mesh
    Object_377: THREE.Mesh
    Object_378: THREE.Mesh
    Object_380: THREE.Mesh
    Object_382: THREE.Mesh
    Object_384: THREE.Mesh
    Object_386: THREE.Mesh
    Object_388: THREE.Mesh
    Object_390: THREE.Mesh
    Object_392: THREE.Mesh
    Object_394: THREE.Mesh
    Object_395: THREE.Mesh
    Object_397: THREE.Mesh
    Object_398: THREE.Mesh
    Object_400: THREE.Mesh
    Object_401: THREE.Mesh
    Object_403: THREE.Mesh
    Object_404: THREE.Mesh
    Object_406: THREE.Mesh
    Object_407: THREE.Mesh
    Object_409: THREE.Mesh
    Object_410: THREE.Mesh
    Object_412: THREE.Mesh
    Object_413: THREE.Mesh
    Object_415: THREE.Mesh
    Object_416: THREE.Mesh
    Object_418: THREE.Mesh
    Object_419: THREE.Mesh
    Object_421: THREE.Mesh
    Object_422: THREE.Mesh
    Object_424: THREE.Mesh
    Object_425: THREE.Mesh
    Object_427: THREE.Mesh
    Object_429: THREE.Mesh
    Object_431: THREE.Mesh
    Object_433: THREE.Mesh
    Object_435: THREE.Mesh
    Object_437: THREE.Mesh
  }
  materials: {
    wall2: THREE.MeshStandardMaterial
    Shop: THREE.MeshStandardMaterial
    Menu: THREE.MeshStandardMaterial
    Emmision: THREE.MeshStandardMaterial
    tbjr_material: THREE.MeshStandardMaterial
    material_0: THREE.MeshStandardMaterial
    Wood: THREE.MeshStandardMaterial
    gradient_glossy: THREE.MeshPhysicalMaterial
  }
}

export function CoffeeShopNew(props: JSX.IntrinsicElements['group']) {
  const [modelError, setModelError] = useState<string | null>(null);
  const { nodes, materials } = useGLTF(MODEL_URL) as GLTFResult
  
  useEffect(() => {
    const handleError = (error: ErrorEvent) => {
      console.error('Error loading model:', error);
      setModelError('Failed to load 3D model');
    };

    window.addEventListener('error', handleError);
    return () => window.removeEventListener('error', handleError);
  }, []);

  // If there's an error loading the model
  if (modelError) {
    return <group {...props}><mesh><boxGeometry args={[1, 1, 1]} /><meshStandardMaterial color="red" /></mesh></group>;
  }
  
  return (
    <group {...props} dispose={null}>
      <group name="Isometric_cafe_202" position={[0, 0.064, 0]}>
        <mesh
          name="Object_4"
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.wall2}
        />
        <mesh
          name="Object_5"
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.Shop}
        />
        <mesh
          name="Object_6"
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.Menu}
        />
        <mesh
          name="Object_7"
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.Emmision}
        />
        <group name="Cube_8" position={[0.742, 0.946, -0.479]}>
          <mesh
            name="Object_9"
            castShadow
            receiveShadow
            geometry={nodes.Object_9.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            name="Object_11"
            castShadow
            receiveShadow
            geometry={nodes.Object_11.geometry}
            material={materials.tbjr_material}
            position={[-0.049, 0.002, 0.046]}
            rotation={[0, -0.392, 0]}
          />
          <mesh
            name="Object_13"
            castShadow
            receiveShadow
            geometry={nodes.Object_13.geometry}
            material={materials.tbjr_material}
            position={[-0.053, 0.002, -0.053]}
            rotation={[0, -0.392, 0]}
          />
          <mesh
            name="Object_15"
            castShadow
            receiveShadow
            geometry={nodes.Object_15.geometry}
            material={materials.tbjr_material}
            position={[0.059, 0.002, 0.046]}
            rotation={[0, -0.392, 0]}
          />
          <mesh
            name="Object_17"
            castShadow
            receiveShadow
            geometry={nodes.Object_17.geometry}
            material={materials.material_0}
            position={[0.055, 0.002, -0.053]}
            rotation={[0, -0.392, 0]}
          />
          <mesh
            name="Object_19"
            castShadow
            receiveShadow
            geometry={nodes.Object_19.geometry}
            material={materials.tbjr_material}
            position={[-0.049, 0.041, 0.046]}
            rotation={[0.165, -0.969, -0.017]}
          />
          <mesh
            name="Object_21"
            castShadow
            receiveShadow
            geometry={nodes.Object_21.geometry}
            material={materials.tbjr_material}
            position={[-0.053, 0.038, -0.053]}
            rotation={[-0.231, -0.35, -0.2]}
          />
          <mesh
            name="Object_23"
            castShadow
            receiveShadow
            geometry={nodes.Object_23.geometry}
            material={materials.tbjr_material}
            position={[0.059, 0.041, 0.046]}
            rotation={[0.149, -0.293, 0.042]}
          />
          <mesh
            name="Object_25"
            castShadow
            receiveShadow
            geometry={nodes.Object_25.geometry}
            material={materials.tbjr_material}
            position={[0.055, 0.041, -0.053]}
            rotation={[-0.173, 0.438, 0.042]}
          />
        </group>
        <group name="Cube002_10" position={[-0.583, 0.749, -0.861]}>
          <mesh
            name="Object_27"
            castShadow
            receiveShadow
            geometry={nodes.Object_27.geometry}
            material={materials.Shop}
          />
          <group name="Cube003_9" position={[0, -0.009, -0.058]}>
            <mesh
              name="Object_29"
              castShadow
              receiveShadow
              geometry={nodes.Object_29.geometry}
              material={materials.Wood}
            />
            <mesh
              name="Object_30"
              castShadow
              receiveShadow
              geometry={nodes.Object_30.geometry}
              material={materials.Emmision}
            />
            <mesh
              name="Object_31"
              castShadow
              receiveShadow
              geometry={nodes.Object_31.geometry}
              material={materials.Shop}
            />
          </group>
        </group>
        <group name="Cube035_16" position={[0.024, 1.514, -0.837]} rotation={[0, 0.1, 0]}>
          <mesh
            name="Object_33"
            castShadow
            receiveShadow
            geometry={nodes.Object_33.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            name="Object_35"
            castShadow
            receiveShadow
            geometry={nodes.Object_35.geometry}
            material={materials.tbjr_material}
            position={[0.237, 0, 0.113]}
            rotation={[0, -0.21, 0]}
          />
          <mesh
            name="Object_37"
            castShadow
            receiveShadow
            geometry={nodes.Object_37.geometry}
            material={materials.tbjr_material}
            position={[0.241, 0, 0.024]}
            rotation={[0, -0.253, 0]}
          />
          <mesh
            name="Object_39"
            castShadow
            receiveShadow
            geometry={nodes.Object_39.geometry}
            material={materials.tbjr_material}
            position={[0.116, 0, 0.1]}
            rotation={[0, 0.001, 0]}
          />
          <mesh
            name="Object_41"
            castShadow
            receiveShadow
            geometry={nodes.Object_41.geometry}
            material={materials.tbjr_material}
            position={[0.124, 0, 0.013]}
            rotation={[0, -0.1, 0]}
          />
          <mesh
            name="Object_43"
            castShadow
            receiveShadow
            geometry={nodes.Object_43.geometry}
            material={materials.tbjr_material}
            position={[-0.009, 0, 0.088]}
            rotation={[0, -0.216, 0]}
          />
        </group>
        <group name="Cube047_29" position={[0.74, 0.424, 0.384]} rotation={[0, 1.523, 0]}>
          <mesh
            name="Object_45"
            castShadow
            receiveShadow
            geometry={nodes.Object_45.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            name="Object_47"
            castShadow
            receiveShadow
            geometry={nodes.Object_47.geometry}
            material={materials.tbjr_material}
            position={[-0.202, 0.383, 0.037]}
            rotation={[0, -1.523, 0]}
          />
          <mesh
            name="Object_49"
            castShadow
            receiveShadow
            geometry={nodes.Object_49.geometry}
            material={materials.tbjr_material}
            position={[0.007, 0.383, 0]}
            rotation={[0, 0.048, 0]}
          />
          <mesh
            name="Object_51"
            castShadow
            receiveShadow
            geometry={nodes.Object_51.geometry}
            material={materials.tbjr_material}
            position={[-0.018, 0.19, 0.001]}
            rotation={[0, 0.112, 0]}
          />
          <mesh
            name="Object_53"
            castShadow
            receiveShadow
            geometry={nodes.Object_53.geometry}
            material={materials.tbjr_material}
            position={[-0.126, 0.19, 0.006]}
            rotation={[0, -0.055, 0]}
          />
          <mesh
            name="Object_55"
            castShadow
            receiveShadow
            geometry={nodes.Object_55.geometry}
            material={materials.tbjr_material}
            position={[-0.234, 0.19, 0.012]}
            rotation={[0, -0.004, 0]}
          />
          <mesh
            name="Object_57"
            castShadow
            receiveShadow
            geometry={nodes.Object_57.geometry}
            material={materials.tbjr_material}
            position={[-0.114, 0, 0.006]}
            rotation={[0, 0.223, 0]}
          />
          <mesh
            name="Object_59"
            castShadow
            receiveShadow
            geometry={nodes.Object_59.geometry}
            material={materials.tbjr_material}
            position={[-0.233, 0, 0.011]}
            rotation={[0, -0.081, 0]}
          />
          <mesh
            name="Object_61"
            castShadow
            receiveShadow
            geometry={nodes.Object_61.geometry}
            material={materials.tbjr_material}
            position={[-0.076, 0.359, -0.005]}
            rotation={[0, -1.523, 0]}
          />
          <mesh
            name="Object_63"
            castShadow
            receiveShadow
            geometry={nodes.Object_63.geometry}
            material={materials.tbjr_material}
            position={[-0.191, 0.352, -0.054]}
            rotation={[0, -0.198, 0]}
          />
          <mesh
            name="Object_65"
            castShadow
            receiveShadow
            geometry={nodes.Object_65.geometry}
            material={materials.tbjr_material}
            position={[-0.005, -0.243, 0.003]}
            rotation={[0, -1.243, 0]}
          />
          <mesh
            name="Object_67"
            castShadow
            receiveShadow
            geometry={nodes.Object_67.geometry}
            material={materials.tbjr_material}
            position={[-0.118, -0.243, 0.059]}
            rotation={[-Math.PI, 0.228, -Math.PI]}
          />
          <mesh
            name="Object_69"
            castShadow
            receiveShadow
            geometry={nodes.Object_69.geometry}
            material={materials.tbjr_material}
            position={[-0.19, -0.243, -0.03]}
            rotation={[-Math.PI, -0.188, -Math.PI]}
          />
        </group>
        <group name="Cube062_42" position={[-0.858, 0.546, 0.854]}>
          <mesh
            name="Object_71"
            castShadow
            receiveShadow
            geometry={nodes.Object_71.geometry}
            material={materials.tbjr_material}
          />
          <group
            name="Cylinder079_38"
            position={[-0.037, 0.027, -0.702]}
            rotation={[0, -0.392, 0]}
            scale={[1.717, 1, 1.717]}>
            <mesh
              name="Object_87"
              castShadow
              receiveShadow
              geometry={nodes.Object_87.geometry}
              material={materials.tbjr_material}
            />
            <mesh
              name="Object_89"
              castShadow
              receiveShadow
              geometry={nodes.Object_89.geometry}
              material={materials.tbjr_material}
              position={[0.004, 0.029, 0.001]}
              rotation={[-Math.PI, 0.586, -Math.PI]}
              scale={[0.752, 1.291, 0.752]}
            />
          </group>
          <group
            name="Cylinder080_41"
            position={[-0.003, 0.027, -0.222]}
            rotation={[0, -0.392, 0]}
            scale={[1.717, 1, 1.717]}>
            <mesh
              name="Object_91"
              castShadow
              receiveShadow
              geometry={nodes.Object_91.geometry}
              material={materials.tbjr_material}
            />
            <mesh
              name="Object_93"
              castShadow
              receiveShadow
              geometry={nodes.Object_93.geometry}
              material={materials.tbjr_material}
              position={[-0.009, 0.024, -0.017]}
              rotation={[0.272, 0.376, -0.079]}
              scale={[0.583, 0.983, 0.61]}
            />
            <mesh
              name="Object_95"
              castShadow
              receiveShadow
              geometry={nodes.Object_95.geometry}
              material={materials.tbjr_material}
              position={[0.011, 0.024, 0.018]}
              rotation={[2.869, -0.376, 3.063]}
              scale={[0.583, 0.983, 0.61]}
            />
          </group>
          <mesh
            name="Object_73"
            castShadow
            receiveShadow
            geometry={nodes.Object_73.geometry}
            material={materials.tbjr_material}
            position={[0.274, -0.255, 0.037]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            name="Object_75"
            castShadow
            receiveShadow
            geometry={nodes.Object_75.geometry}
            material={materials.tbjr_material}
            position={[-0.021, -0.202, -1.159]}
          />
          <mesh
            name="Object_77"
            castShadow
            receiveShadow
            geometry={nodes.Object_77.geometry}
            material={materials.tbjr_material}
            position={[0.139, -0.202, -0.69]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh
            name="Object_79"
            castShadow
            receiveShadow
            geometry={nodes.Object_79.geometry}
            material={materials.tbjr_material}
            position={[0.14, -0.202, -0.286]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh
            name="Object_81"
            castShadow
            receiveShadow
            geometry={nodes.Object_81.geometry}
            material={materials.tbjr_material}
            position={[0.492, -0.202, 0.023]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh
            name="Object_83"
            castShadow
            receiveShadow
            geometry={nodes.Object_83.geometry}
            material={materials.tbjr_material}
            position={[0.016, 0.027, -0.583]}
            rotation={[-Math.PI, 0.639, -Math.PI]}
          />
          <mesh
            name="Object_85"
            castShadow
            receiveShadow
            geometry={nodes.Object_85.geometry}
            material={materials.tbjr_material}
            position={[-0.053, 0.027, -0.355]}
            rotation={[0, -0.859, 0]}
          />
        </group>
        <group name="Cylinder010_53" position={[0.493, 1.168, -0.792]}>
          <mesh
            name="Object_101"
            castShadow
            receiveShadow
            geometry={nodes.Object_101.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            name="Object_103"
            castShadow
            receiveShadow
            geometry={nodes.Object_103.geometry}
            material={materials.tbjr_material}
            position={[0.002, 0.061, 0.039]}
          />
          <mesh
            name="Object_105"
            castShadow
            receiveShadow
            geometry={nodes.Object_105.geometry}
            material={materials.tbjr_material}
            position={[0.04, 0.061, -0.021]}
            rotation={[0, -0.959, 0]}
          />
          <mesh
            name="Object_107"
            castShadow
            receiveShadow
            geometry={nodes.Object_107.geometry}
            material={materials.tbjr_material}
            position={[-0.037, 0.061, -0.024]}
            rotation={[0, 0.913, 0]}
          />
          <mesh
            name="Object_109"
            castShadow
            receiveShadow
            geometry={nodes.Object_109.geometry}
            material={materials.tbjr_material}
            position={[0.036, 0.093, 0.019]}
            rotation={[0, 1.015, 0]}
          />
          <mesh
            name="Object_111"
            castShadow
            receiveShadow
            geometry={nodes.Object_111.geometry}
            material={materials.tbjr_material}
            position={[0.006, 0.093, -0.045]}
            rotation={[0, 0.056, 0]}
          />
          <mesh
            name="Object_113"
            castShadow
            receiveShadow
            geometry={nodes.Object_113.geometry}
            material={materials.tbjr_material}
            position={[-0.037, 0.093, 0.019]}
            rotation={[-Math.PI, 1.214, -Math.PI]}
          />
          <mesh
            name="Object_115"
            castShadow
            receiveShadow
            geometry={nodes.Object_115.geometry}
            material={materials.tbjr_material}
            position={[0.024, 0.126, 0.005]}
            rotation={[0, 1.321, 0]}
          />
          <mesh
            name="Object_117"
            castShadow
            receiveShadow
            geometry={nodes.Object_117.geometry}
            material={materials.tbjr_material}
            position={[-0.023, 0.126, -0.007]}
            rotation={[0, 1.321, 0]}
          />
        </group>
        <group name="Cylinder011_65" position={[-0.372, 1.543, -0.756]}>
          <mesh
            name="Object_119"
            castShadow
            receiveShadow
            geometry={nodes.Object_119.geometry}
            material={materials.gradient_glossy}
          />
          <mesh
            name="Object_121"
            castShadow
            receiveShadow
            geometry={nodes.Object_121.geometry}
            material={materials.tbjr_material}
            position={[-0.378, 0.037, -0.001]}
            rotation={[0, 0.288, 0]}
          />
          <mesh
            name="Object_123"
            castShadow
            receiveShadow
            geometry={nodes.Object_123.geometry}
            material={materials.tbjr_material}
            position={[-0.281, 0.029, 0.022]}
            rotation={[0, -0.032, 0]}
          />
          <mesh
            name="Object_125"
            castShadow
            receiveShadow
            geometry={nodes.Object_125.geometry}
            material={materials.tbjr_material}
            position={[-0.005, 0.195, 0.004]}
            rotation={[0, -0.237, 0]}
          />
          <mesh
            name="Object_127"
            castShadow
            receiveShadow
            geometry={nodes.Object_127.geometry}
            material={materials.tbjr_material}
            position={[-0.11, 0.195, 0.005]}
            rotation={[0, 0.13, 0]}
          />
          <mesh
            name="Object_129"
            castShadow
            receiveShadow
            geometry={nodes.Object_129.geometry}
            material={materials.tbjr_material}
            position={[-0.009, 0.195, -0.071]}
            rotation={[0, 0.106, 0]}
          />
          <mesh
            name="Object_131"
            castShadow
            receiveShadow
            geometry={nodes.Object_131.geometry}
            material={materials.tbjr_material}
            position={[-0.102, 0.195, -0.071]}
            rotation={[0, -0.179, 0]}
          />
          <mesh
            name="Object_133"
            castShadow
            receiveShadow
            geometry={nodes.Object_133.geometry}
            material={materials.gradient_glossy}
            position={[-0.096, 0, 0]}
            rotation={[0, -0.317, 0]}
          />
          <mesh
            name="Object_135"
            castShadow
            receiveShadow
            geometry={nodes.Object_135.geometry}
            material={materials.gradient_glossy}
            position={[-0.191, 0, 0]}
            rotation={[0, 0.301, 0]}
          />
          <mesh
            name="Object_137"
            castShadow
            receiveShadow
            geometry={nodes.Object_137.geometry}
            material={materials.gradient_glossy}
            position={[-0.307, 0.166, -0.011]}
            rotation={[0, -0.52, 0]}
          />
          <mesh
            name="Object_139"
            castShadow
            receiveShadow
            geometry={nodes.Object_139.geometry}
            material={materials.gradient_glossy}
            position={[-0.401, 0.166, -0.011]}
            rotation={[0, 0.301, 0]}
          />
          <mesh
            name="Object_141"
            castShadow
            receiveShadow
            geometry={nodes.Object_141.geometry}
            material={materials.gradient_glossy}
            position={[-0.205, 0.166, -0.011]}
            rotation={[0, -0.046, 0]}
          />
        </group>
        <group
          name="Cylinder025_84"
          position={[0.756, 1.172, 0.432]}
          rotation={[Math.PI, -1.149, Math.PI]}>
          <mesh
            name="Object_149"
            castShadow
            receiveShadow
            geometry={nodes.Object_149.geometry}
            material={materials.gradient_glossy}
          />
          <mesh
            name="Object_151"
            castShadow
            receiveShadow
            geometry={nodes.Object_151.geometry}
            material={materials.tbjr_material}
            position={[-0.012, 0.175, 0.014]}
            rotation={[0, 0.39, 0]}
          />
          <mesh
            name="Object_153"
            castShadow
            receiveShadow
            geometry={nodes.Object_153.geometry}
            material={materials.tbjr_material}
            position={[0.083, 0.175, -0.03]}
            rotation={[0, 0.517, 0]}
          />
          <mesh
            name="Object_155"
            castShadow
            receiveShadow
            geometry={nodes.Object_155.geometry}
            material={materials.tbjr_material}
            position={[0.212, 0.321, -0.105]}
            rotation={[0, 0.39, 0]}
          />
          <mesh
            name="Object_157"
            castShadow
            receiveShadow
            geometry={nodes.Object_157.geometry}
            material={materials.tbjr_material}
            position={[0.307, 0.321, -0.15]}
            rotation={[0, 0.517, 0]}
          />
          <mesh
            name="Object_159"
            castShadow
            receiveShadow
            geometry={nodes.Object_159.geometry}
            material={materials.gradient_glossy}
            position={[0.185, 0.145, -0.083]}
            rotation={[0, 0.586, 0]}
          />
          <mesh
            name="Object_161"
            castShadow
            receiveShadow
            geometry={nodes.Object_161.geometry}
            material={materials.gradient_glossy}
            position={[0.282, 0.145, -0.127]}
            rotation={[0, 0.052, 0]}
          />
          <mesh
            name="Object_163"
            castShadow
            receiveShadow
            geometry={nodes.Object_163.geometry}
            material={materials.gradient_glossy}
            position={[0.282, 0, -0.127]}
            rotation={[0, 0.052, 0]}
          />
          <mesh
            name="Object_165"
            castShadow
            receiveShadow
            geometry={nodes.Object_165.geometry}
            material={materials.gradient_glossy}
            position={[0.189, 0, -0.085]}
            rotation={[0, 0.052, 0]}
          />
          <mesh
            name="Object_167"
            castShadow
            receiveShadow
            geometry={nodes.Object_167.geometry}
            material={materials.gradient_glossy}
            position={[0.095, 0, -0.042]}
            rotation={[0, 0.773, 0]}
          />
          <mesh
            name="Object_169"
            castShadow
            receiveShadow
            geometry={nodes.Object_169.geometry}
            material={materials.gradient_glossy}
            position={[-0.02, 0.272, 0.036]}
            rotation={[0, 0.586, 0]}
          />
          <mesh
            name="Object_171"
            castShadow
            receiveShadow
            geometry={nodes.Object_171.geometry}
            material={materials.gradient_glossy}
            position={[0.024, 0.272, 0.016]}
            rotation={[0, 0.052, 0]}
          />
          <mesh
            name="Object_173"
            castShadow
            receiveShadow
            geometry={nodes.Object_173.geometry}
            material={materials.gradient_glossy}
            position={[0.08, 0.272, -0.009]}
            rotation={[0, 0.586, 0]}
          />
          <mesh
            name="Object_175"
            castShadow
            receiveShadow
            geometry={nodes.Object_175.geometry}
            material={materials.gradient_glossy}
            position={[0.124, 0.272, -0.029]}
            rotation={[0, 0.052, 0]}
          />
          <mesh
            name="Object_177"
            castShadow
            receiveShadow
            geometry={nodes.Object_177.geometry}
            material={materials.gradient_glossy}
            position={[-0.034, 0.291, -0.041]}
            rotation={[0, 0.474, 0]}
          />
          <mesh
            name="Object_179"
            castShadow
            receiveShadow
            geometry={nodes.Object_179.geometry}
            material={materials.gradient_glossy}
            position={[0.056, 0.291, -0.082]}
            rotation={[0, 0.16, 0]}
          />
        </group>
        <group name="Cylinder056_86" position={[-0.111, 0.663, -0.698]}>
          <mesh
            name="Object_181"
            castShadow
            receiveShadow
            geometry={nodes.Object_181.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            name="Object_183"
            castShadow
            receiveShadow
            geometry={nodes.Object_183.geometry}
            material={materials.tbjr_material}
            position={[0, 0.1, 0]}
          />
        </group>
        <group name="Cylinder057_89" position={[0.099, 0.663, -0.698]}>
          <mesh
            name="Object_185"
            castShadow
            receiveShadow
            geometry={nodes.Object_185.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            name="Object_187"
            castShadow
            receiveShadow
            geometry={nodes.Object_187.geometry}
            material={materials.tbjr_material}
            position={[-0.036, 0.111, -0.005]}
            rotation={[0.011, 0.575, -0.103]}
          />
          <mesh
            name="Object_189"
            castShadow
            receiveShadow
            geometry={nodes.Object_189.geometry}
            material={materials.tbjr_material}
            position={[0.024, 0.111, 0.062]}
            rotation={[0.023, 1.149, -0.118]}
          />
        </group>
        <group name="Cylinder058_94" position={[0.307, 0.663, -0.698]}>
          <mesh
            name="Object_191"
            castShadow
            receiveShadow
            geometry={nodes.Object_191.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            name="Object_193"
            castShadow
            receiveShadow
            geometry={nodes.Object_193.geometry}
            material={materials.tbjr_material}
            position={[-0.042, 0.104, 0.027]}
            rotation={[-0.378, 0.568, 0.788]}
          />
          <mesh
            name="Object_195"
            castShadow
            receiveShadow
            geometry={nodes.Object_195.geometry}
            material={materials.tbjr_material}
            position={[-0.024, 0.096, -0.052]}
            rotation={[0.23, 0.606, -0.087]}
          />
          <mesh
            name="Object_197"
            castShadow
            receiveShadow
            geometry={nodes.Object_197.geometry}
            material={materials.tbjr_material}
            position={[0.063, 0.097, 0.009]}
            rotation={[-0.313, 0.652, 0.455]}
          />
          <mesh
            name="Object_199"
            castShadow
            receiveShadow
            geometry={nodes.Object_199.geometry}
            material={materials.tbjr_material}
            position={[0.008, 0.104, 0.049]}
            rotation={[Math.PI, 1.405, -2.424]}
          />
        </group>
        <group
          name="Cylinder076_98"
          position={[0.007, 0.761, 0.106]}
          rotation={[Math.PI, -1.463, Math.PI]}>
          <mesh
            name="Object_203"
            castShadow
            receiveShadow
            geometry={nodes.Object_203.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            name="Object_205"
            castShadow
            receiveShadow
            geometry={nodes.Object_205.geometry}
            material={materials.tbjr_material}
            position={[-0.024, 0.108, -0.016]}
            rotation={[0.011, 0.575, -0.103]}
            scale={0.86}
          />
          <mesh
            name="Object_207"
            castShadow
            receiveShadow
            geometry={nodes.Object_207.geometry}
            material={materials.tbjr_material}
            position={[0.028, 0.108, 0.041]}
            rotation={[0.023, 1.149, -0.118]}
            scale={0.86}
          />
        </group>
        <group name="Plane_106" position={[-0.052, 1.136, -0.792]}>
          <mesh
            name="Object_209"
            castShadow
            receiveShadow
            geometry={nodes.Object_209.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            name="Object_210"
            castShadow
            receiveShadow
            geometry={nodes.Object_210.geometry}
            material={materials.material_0}
          />
          <mesh
            name="Object_212"
            castShadow
            receiveShadow
            geometry={nodes.Object_212.geometry}
            material={materials.tbjr_material}
            position={[0.052, 0.048, -0.038]}
          />
          <mesh
            name="Object_214"
            castShadow
            receiveShadow
            geometry={nodes.Object_214.geometry}
            material={materials.tbjr_material}
            position={[0.047, 0.048, 0.027]}
          />
          <mesh
            name="Object_216"
            castShadow
            receiveShadow
            geometry={nodes.Object_216.geometry}
            material={materials.tbjr_material}
            position={[-0.047, 0.048, -0.034]}
          />
          <mesh
            name="Object_218"
            castShadow
            receiveShadow
            geometry={nodes.Object_218.geometry}
            material={materials.tbjr_material}
            position={[-0.07, 0.073, 0.04]}
            rotation={[-0.135, 0.683, -0.211]}
          />
          <mesh
            name="Object_220"
            castShadow
            receiveShadow
            geometry={nodes.Object_220.geometry}
            material={materials.tbjr_material}
            position={[0.008, 0.082, 0.042]}
            rotation={[0.127, 0.358, -0.112]}
          />
          <mesh
            name="Object_222"
            castShadow
            receiveShadow
            geometry={nodes.Object_222.geometry}
            material={materials.tbjr_material}
            position={[0.003, 0.08, -0.031]}
            rotation={[-0.007, -0.241, -0.011]}
          />
          <mesh
            name="Object_224"
            castShadow
            receiveShadow
            geometry={nodes.Object_224.geometry}
            material={materials.tbjr_material}
            position={[0, 0.046, 0]}
          />
        </group>
        <group name="Plane002_111" position={[0.196, 1.136, -0.792]}>
          <mesh
            name="Object_226"
            castShadow
            receiveShadow
            geometry={nodes.Object_226.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            name="Object_227"
            castShadow
            receiveShadow
            geometry={nodes.Object_227.geometry}
            material={materials.material_0}
          />
          <mesh
            name="Object_229"
            castShadow
            receiveShadow
            geometry={nodes.Object_229.geometry}
            material={materials.tbjr_material}
            position={[0, 0.046, 0]}
          />
          <mesh
            name="Object_231"
            castShadow
            receiveShadow
            geometry={nodes.Object_231.geometry}
            material={materials.tbjr_material}
            position={[0, 0.06, 0.014]}
          />
          <mesh
            name="Object_233"
            castShadow
            receiveShadow
            geometry={nodes.Object_233.geometry}
            material={materials.tbjr_material}
            position={[-0.056, 0.087, -0.01]}
            rotation={[2.097, -0.701, 2.236]}
          />
          <mesh
            name="Object_235"
            castShadow
            receiveShadow
            geometry={nodes.Object_235.geometry}
            material={materials.tbjr_material}
            position={[0.052, 0.092, -0.01]}
            rotation={[2.049, 0.732, -2.298]}
          />
        </group>
        <group name="Plane005_119" position={[0.73, 1.182, -0.792]}>
          <mesh
            name="Object_237"
            castShadow
            receiveShadow
            geometry={nodes.Object_237.geometry}
            material={materials.tbjr_material}
          />
          <group name="Plane004_118" position={[0, -0.046, 0]}>
            <mesh
              name="Object_251"
              castShadow
              receiveShadow
              geometry={nodes.Object_251.geometry}
              material={materials.tbjr_material}
            />
            <mesh
              name="Object_252"
              castShadow
              receiveShadow
              geometry={nodes.Object_252.geometry}
              material={materials.material_0}
            />
          </group>
          <mesh
            name="Object_239"
            castShadow
            receiveShadow
            geometry={nodes.Object_239.geometry}
            material={materials.tbjr_material}
            position={[0.052, 0.001, -0.038]}
          />
          <mesh
            name="Object_241"
            castShadow
            receiveShadow
            geometry={nodes.Object_241.geometry}
            material={materials.tbjr_material}
            position={[0.047, 0.001, 0.027]}
          />
          <mesh
            name="Object_243"
            castShadow
            receiveShadow
            geometry={nodes.Object_243.geometry}
            material={materials.tbjr_material}
            position={[-0.047, 0.001, -0.034]}
          />
          <mesh
            name="Object_245"
            castShadow
            receiveShadow
            geometry={nodes.Object_245.geometry}
            material={materials.tbjr_material}
            position={[-0.07, 0.027, 0.04]}
            rotation={[-0.135, 0.683, -0.211]}
          />
          <mesh
            name="Object_247"
            castShadow
            receiveShadow
            geometry={nodes.Object_247.geometry}
            material={materials.tbjr_material}
            position={[0.008, 0.036, 0.042]}
            rotation={[0.127, 0.358, -0.112]}
          />
          <mesh
            name="Object_249"
            castShadow
            receiveShadow
            geometry={nodes.Object_249.geometry}
            material={materials.tbjr_material}
            position={[0.003, 0.034, -0.031]}
            rotation={[-0.007, -0.241, -0.011]}
          />
        </group>
        <group name="Plane006_126" position={[0.73, 1.429, -0.792]}>
          <mesh
            name="Object_254"
            castShadow
            receiveShadow
            geometry={nodes.Object_254.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            name="Object_255"
            castShadow
            receiveShadow
            geometry={nodes.Object_255.geometry}
            material={materials.material_0}
          />
          <mesh
            name="Object_257"
            castShadow
            receiveShadow
            geometry={nodes.Object_257.geometry}
            material={materials.tbjr_material}
            position={[0.058, 0.052, 0]}
            rotation={[0, -0.057, 0]}
          />
          <mesh
            name="Object_259"
            castShadow
            receiveShadow
            geometry={nodes.Object_259.geometry}
            material={materials.tbjr_material}
            position={[-0.015, 0.052, 0]}
            rotation={[0, 0.06, 0]}
          />
          <mesh
            name="Object_261"
            castShadow
            receiveShadow
            geometry={nodes.Object_261.geometry}
            material={materials.tbjr_material}
            position={[-0.287, 0.052, 0]}
            rotation={[0, -0.038, 0]}
          />
          <mesh
            name="Object_263"
            castShadow
            receiveShadow
            geometry={nodes.Object_263.geometry}
            material={materials.tbjr_material}
            position={[-0.118, 0.052, -0.034]}
            rotation={[-Math.PI, 1.548, -Math.PI]}
          />
          <mesh
            name="Object_265"
            castShadow
            receiveShadow
            geometry={nodes.Object_265.geometry}
            material={materials.tbjr_material}
            position={[-0.117, 0.052, 0.033]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            name="Object_267"
            castShadow
            receiveShadow
            geometry={nodes.Object_267.geometry}
            material={materials.tbjr_material}
            position={[-0.217, 0.052, 0]}
          />
        </group>
        <group name="Plane007_133" position={[0.082, 0.602, 0.236]}>
          <mesh
            name="Object_269"
            castShadow
            receiveShadow
            geometry={nodes.Object_269.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            name="Object_270"
            castShadow
            receiveShadow
            geometry={nodes.Object_270.geometry}
            material={materials.material_0}
          />
          <mesh
            name="Object_272"
            castShadow
            receiveShadow
            geometry={nodes.Object_272.geometry}
            material={materials.tbjr_material}
            position={[-0.241, 0.027, -0.034]}
          />
          <mesh
            name="Object_274"
            castShadow
            receiveShadow
            geometry={nodes.Object_274.geometry}
            material={materials.tbjr_material}
            position={[-0.166, 0.027, -0.034]}
            rotation={[0, -0.809, 0]}
          />
          <mesh
            name="Object_276"
            castShadow
            receiveShadow
            geometry={nodes.Object_276.geometry}
            material={materials.tbjr_material}
            position={[-0.241, 0.027, 0.034]}
            rotation={[0, -0.945, 0]}
          />
          <mesh
            name="Object_278"
            castShadow
            receiveShadow
            geometry={nodes.Object_278.geometry}
            material={materials.tbjr_material}
            position={[-0.166, 0.027, 0.034]}
            rotation={[0, 0.634, 0]}
          />
          <mesh
            name="Object_280"
            castShadow
            receiveShadow
            geometry={nodes.Object_280.geometry}
            material={materials.tbjr_material}
            position={[-0.095, 0.027, -0.034]}
            rotation={[0, -0.809, 0]}
          />
          <mesh
            name="Object_282"
            castShadow
            receiveShadow
            geometry={nodes.Object_282.geometry}
            material={materials.tbjr_material}
            position={[-0.095, 0.027, 0.034]}
            rotation={[0, 0.634, 0]}
          />
        </group>
        <group name="Plane008_140" position={[0.082, 0.602, 0.411]}>
          <mesh
            name="Object_284"
            castShadow
            receiveShadow
            geometry={nodes.Object_284.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            name="Object_285"
            castShadow
            receiveShadow
            geometry={nodes.Object_285.geometry}
            material={materials.material_0}
          />
          <mesh
            name="Object_287"
            castShadow
            receiveShadow
            geometry={nodes.Object_287.geometry}
            material={materials.tbjr_material}
            position={[-0.238, 0.029, 0.033]}
            rotation={[0, -0.772, 0]}
          />
          <mesh
            name="Object_289"
            castShadow
            receiveShadow
            geometry={nodes.Object_289.geometry}
            material={materials.tbjr_material}
            position={[-0.171, 0.029, -0.032]}
            rotation={[0, -0.459, 0]}
          />
          <mesh
            name="Object_291"
            castShadow
            receiveShadow
            geometry={nodes.Object_291.geometry}
            material={materials.tbjr_material}
            position={[-0.171, 0.029, 0.033]}
            rotation={[0, 0.399, 0]}
          />
          <mesh
            name="Object_293"
            castShadow
            receiveShadow
            geometry={nodes.Object_293.geometry}
            material={materials.tbjr_material}
            position={[-0.238, 0.029, -0.032]}
            rotation={[0, 0.333, 0]}
          />
          <mesh
            name="Object_295"
            castShadow
            receiveShadow
            geometry={nodes.Object_295.geometry}
            material={materials.tbjr_material}
            position={[-0.106, 0.029, -0.032]}
            rotation={[0, 0.464, 0]}
          />
          <mesh
            name="Object_297"
            castShadow
            receiveShadow
            geometry={nodes.Object_297.geometry}
            material={materials.tbjr_material}
            position={[-0.106, 0.029, 0.033]}
            rotation={[0, -0.085, 0]}
          />
        </group>
        <group name="Plane009_145" position={[0.082, 0.602, 0.057]}>
          <mesh
            name="Object_299"
            castShadow
            receiveShadow
            geometry={nodes.Object_299.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            name="Object_300"
            castShadow
            receiveShadow
            geometry={nodes.Object_300.geometry}
            material={materials.material_0}
          />
          <mesh
            name="Object_302"
            castShadow
            receiveShadow
            geometry={nodes.Object_302.geometry}
            material={materials.tbjr_material}
            position={[-0.218, 0.03, -0.027]}
          />
          <mesh
            name="Object_304"
            castShadow
            receiveShadow
            geometry={nodes.Object_304.geometry}
            material={materials.tbjr_material}
            position={[-0.156, 0.03, 0.024]}
          />
          <mesh
            name="Object_306"
            castShadow
            receiveShadow
            geometry={nodes.Object_306.geometry}
            material={materials.tbjr_material}
            position={[-0.226, 0.048, 0.033]}
            rotation={[0.871, -0.736, 0.468]}
          />
          <mesh
            name="Object_308"
            castShadow
            receiveShadow
            geometry={nodes.Object_308.geometry}
            material={materials.tbjr_material}
            position={[-0.099, 0.03, -0.03]}
          />
        </group>
        <group name="Plane010_152" position={[0.082, 0.383, 0.41]}>
          <mesh
            name="Object_310"
            castShadow
            receiveShadow
            geometry={nodes.Object_310.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            name="Object_311"
            castShadow
            receiveShadow
            geometry={nodes.Object_311.geometry}
            material={materials.material_0}
          />
          <mesh
            name="Object_313"
            castShadow
            receiveShadow
            geometry={nodes.Object_313.geometry}
            material={materials.tbjr_material}
            position={[-0.241, 0.027, -0.034]}
          />
          <mesh
            name="Object_315"
            castShadow
            receiveShadow
            geometry={nodes.Object_315.geometry}
            material={materials.tbjr_material}
            position={[-0.166, 0.027, -0.034]}
            rotation={[0, -0.809, 0]}
          />
          <mesh
            name="Object_317"
            castShadow
            receiveShadow
            geometry={nodes.Object_317.geometry}
            material={materials.tbjr_material}
            position={[-0.241, 0.027, 0.034]}
            rotation={[0, -0.945, 0]}
          />
          <mesh
            name="Object_319"
            castShadow
            receiveShadow
            geometry={nodes.Object_319.geometry}
            material={materials.tbjr_material}
            position={[-0.166, 0.027, 0.034]}
            rotation={[0, 0.634, 0]}
          />
          <mesh
            name="Object_321"
            castShadow
            receiveShadow
            geometry={nodes.Object_321.geometry}
            material={materials.tbjr_material}
            position={[-0.095, 0.027, -0.034]}
            rotation={[0, -0.809, 0]}
          />
          <mesh
            name="Object_323"
            castShadow
            receiveShadow
            geometry={nodes.Object_323.geometry}
            material={materials.tbjr_material}
            position={[-0.095, 0.027, 0.034]}
            rotation={[0, 0.634, 0]}
          />
        </group>
        <group name="Plane011_157" position={[0.082, 0.383, 0.236]}>
          <mesh
            name="Object_325"
            castShadow
            receiveShadow
            geometry={nodes.Object_325.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            name="Object_326"
            castShadow
            receiveShadow
            geometry={nodes.Object_326.geometry}
            material={materials.material_0}
          />
          <mesh
            name="Object_328"
            castShadow
            receiveShadow
            geometry={nodes.Object_328.geometry}
            material={materials.tbjr_material}
            position={[-0.235, 0.022, 0.036]}
          />
          <mesh
            name="Object_330"
            castShadow
            receiveShadow
            geometry={nodes.Object_330.geometry}
            material={materials.tbjr_material}
            position={[-0.192, 0.022, -0.022]}
            rotation={[-Math.PI, 1.235, -Math.PI]}
          />
          <mesh
            name="Object_332"
            castShadow
            receiveShadow
            geometry={nodes.Object_332.geometry}
            material={materials.tbjr_material}
            position={[-0.148, 0.022, 0.037]}
            rotation={[0, 0.691, 0]}
          />
          <mesh
            name="Object_334"
            castShadow
            receiveShadow
            geometry={nodes.Object_334.geometry}
            material={materials.tbjr_material}
            position={[-0.106, 0.022, -0.022]}
            rotation={[0, 0.746, 0]}
          />
        </group>
        <group name="Plane012_164" position={[0.082, 0.383, 0.057]}>
          <mesh
            name="Object_336"
            castShadow
            receiveShadow
            geometry={nodes.Object_336.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            name="Object_337"
            castShadow
            receiveShadow
            geometry={nodes.Object_337.geometry}
            material={materials.material_0}
          />
          <mesh
            name="Object_339"
            castShadow
            receiveShadow
            geometry={nodes.Object_339.geometry}
            material={materials.tbjr_material}
            position={[-0.236, 0.03, -0.031]}
          />
          <mesh
            name="Object_341"
            castShadow
            receiveShadow
            geometry={nodes.Object_341.geometry}
            material={materials.tbjr_material}
            position={[-0.236, 0.03, 0.034]}
          />
          <mesh
            name="Object_343"
            castShadow
            receiveShadow
            geometry={nodes.Object_343.geometry}
            material={materials.tbjr_material}
            position={[-0.168, 0.03, -0.031]}
          />
          <mesh
            name="Object_345"
            castShadow
            receiveShadow
            geometry={nodes.Object_345.geometry}
            material={materials.tbjr_material}
            position={[-0.168, 0.03, 0.034]}
          />
          <mesh
            name="Object_347"
            castShadow
            receiveShadow
            geometry={nodes.Object_347.geometry}
            material={materials.tbjr_material}
            position={[-0.098, 0.03, -0.031]}
          />
          <mesh
            name="Object_349"
            castShadow
            receiveShadow
            geometry={nodes.Object_349.geometry}
            material={materials.tbjr_material}
            position={[-0.098, 0.03, 0.034]}
          />
        </group>
        <group name="Plane013_171" position={[0.082, 0.166, 0.235]}>
          <mesh
            name="Object_351"
            castShadow
            receiveShadow
            geometry={nodes.Object_351.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            name="Object_352"
            castShadow
            receiveShadow
            geometry={nodes.Object_352.geometry}
            material={materials.material_0}
          />
          <mesh
            name="Object_354"
            castShadow
            receiveShadow
            geometry={nodes.Object_354.geometry}
            material={materials.tbjr_material}
            position={[-0.236, 0.03, -0.031]}
          />
          <mesh
            name="Object_356"
            castShadow
            receiveShadow
            geometry={nodes.Object_356.geometry}
            material={materials.tbjr_material}
            position={[-0.236, 0.03, 0.034]}
          />
          <mesh
            name="Object_358"
            castShadow
            receiveShadow
            geometry={nodes.Object_358.geometry}
            material={materials.tbjr_material}
            position={[-0.168, 0.03, -0.031]}
          />
          <mesh
            name="Object_360"
            castShadow
            receiveShadow
            geometry={nodes.Object_360.geometry}
            material={materials.tbjr_material}
            position={[-0.168, 0.03, 0.034]}
          />
          <mesh
            name="Object_362"
            castShadow
            receiveShadow
            geometry={nodes.Object_362.geometry}
            material={materials.tbjr_material}
            position={[-0.098, 0.03, -0.031]}
          />
          <mesh
            name="Object_364"
            castShadow
            receiveShadow
            geometry={nodes.Object_364.geometry}
            material={materials.tbjr_material}
            position={[-0.098, 0.03, 0.034]}
          />
        </group>
        <group name="Plane014_176" position={[0.082, 0.166, 0.41]}>
          <mesh
            name="Object_366"
            castShadow
            receiveShadow
            geometry={nodes.Object_366.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            name="Object_367"
            castShadow
            receiveShadow
            geometry={nodes.Object_367.geometry}
            material={materials.material_0}
          />
          <mesh
            name="Object_369"
            castShadow
            receiveShadow
            geometry={nodes.Object_369.geometry}
            material={materials.tbjr_material}
            position={[-0.218, 0.03, -0.027]}
          />
          <mesh
            name="Object_371"
            castShadow
            receiveShadow
            geometry={nodes.Object_371.geometry}
            material={materials.tbjr_material}
            position={[-0.156, 0.03, 0.024]}
          />
          <mesh
            name="Object_373"
            castShadow
            receiveShadow
            geometry={nodes.Object_373.geometry}
            material={materials.tbjr_material}
            position={[-0.226, 0.048, 0.033]}
            rotation={[0.871, -0.736, 0.468]}
          />
          <mesh
            name="Object_375"
            castShadow
            receiveShadow
            geometry={nodes.Object_375.geometry}
            material={materials.tbjr_material}
            position={[-0.099, 0.03, -0.03]}
          />
        </group>
        <group name="Plane015_183" position={[0.082, 0.165, 0.058]}>
          <mesh
            name="Object_377"
            castShadow
            receiveShadow
            geometry={nodes.Object_377.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            name="Object_378"
            castShadow
            receiveShadow
            geometry={nodes.Object_378.geometry}
            material={materials.material_0}
          />
          <mesh
            name="Object_380"
            castShadow
            receiveShadow
            geometry={nodes.Object_380.geometry}
            material={materials.tbjr_material}
            position={[-0.238, 0.029, -0.032]}
            rotation={[0, 0.333, 0]}
          />
          <mesh
            name="Object_382"
            castShadow
            receiveShadow
            geometry={nodes.Object_382.geometry}
            material={materials.tbjr_material}
            position={[-0.238, 0.029, 0.033]}
            rotation={[0, -0.772, 0]}
          />
          <mesh
            name="Object_384"
            castShadow
            receiveShadow
            geometry={nodes.Object_384.geometry}
            material={materials.tbjr_material}
            position={[-0.171, 0.029, -0.032]}
            rotation={[0, -0.459, 0]}
          />
          <mesh
            name="Object_386"
            castShadow
            receiveShadow
            geometry={nodes.Object_386.geometry}
            material={materials.tbjr_material}
            position={[-0.171, 0.029, 0.033]}
            rotation={[0, 0.399, 0]}
          />
          <mesh
            name="Object_388"
            castShadow
            receiveShadow
            geometry={nodes.Object_388.geometry}
            material={materials.tbjr_material}
            position={[-0.106, 0.029, -0.032]}
            rotation={[0, 0.464, 0]}
          />
          <mesh
            name="Object_390"
            castShadow
            receiveShadow
            geometry={nodes.Object_390.geometry}
            material={materials.tbjr_material}
            position={[-0.106, 0.029, 0.033]}
            rotation={[0, -0.085, 0]}
          />
        </group>
        <group name="Plane016_194" position={[0.854, 1.894, -0.886]}>
          <mesh
            name="Object_392"
            castShadow
            receiveShadow
            geometry={nodes.Object_392.geometry}
            material={materials.Shop}
          />
          <group name="Sphere_184" position={[0, -0.231, 0.92]}>
            <mesh
              name="Object_394"
              castShadow
              receiveShadow
              geometry={nodes.Object_394.geometry}
              material={materials.Shop}
            />
            <mesh
              name="Object_395"
              castShadow
              receiveShadow
              geometry={nodes.Object_395.geometry}
              material={materials.Emmision}
            />
          </group>
          <group name="Sphere001_185" position={[0, -0.175, 1.085]}>
            <mesh
              name="Object_397"
              castShadow
              receiveShadow
              geometry={nodes.Object_397.geometry}
              material={materials.Shop}
            />
            <mesh
              name="Object_398"
              castShadow
              receiveShadow
              geometry={nodes.Object_398.geometry}
              material={materials.Emmision}
            />
          </group>
          <group name="Sphere002_186" position={[0, -0.097, 1.24]}>
            <mesh
              name="Object_400"
              castShadow
              receiveShadow
              geometry={nodes.Object_400.geometry}
              material={materials.Shop}
            />
            <mesh
              name="Object_401"
              castShadow
              receiveShadow
              geometry={nodes.Object_401.geometry}
              material={materials.Emmision}
            />
          </group>
          <group name="Sphere004_187" position={[0, -0.18, 1.426]}>
            <mesh
              name="Object_403"
              castShadow
              receiveShadow
              geometry={nodes.Object_403.geometry}
              material={materials.Shop}
            />
            <mesh
              name="Object_404"
              castShadow
              receiveShadow
              geometry={nodes.Object_404.geometry}
              material={materials.Emmision}
            />
          </group>
          <group name="Sphere005_188" position={[0, -0.197, 1.632]}>
            <mesh
              name="Object_406"
              castShadow
              receiveShadow
              geometry={nodes.Object_406.geometry}
              material={materials.Shop}
            />
            <mesh
              name="Object_407"
              castShadow
              receiveShadow
              geometry={nodes.Object_407.geometry}
              material={materials.Emmision}
            />
          </group>
          <group name="Sphere006_189" position={[0, -0.118, 1.797]}>
            <mesh
              name="Object_409"
              castShadow
              receiveShadow
              geometry={nodes.Object_409.geometry}
              material={materials.Shop}
            />
            <mesh
              name="Object_410"
              castShadow
              receiveShadow
              geometry={nodes.Object_410.geometry}
              material={materials.Emmision}
            />
          </group>
          <group name="Sphere007_190" position={[0, -0.154, 0.743]}>
            <mesh
              name="Object_412"
              castShadow
              receiveShadow
              geometry={nodes.Object_412.geometry}
              material={materials.Shop}
            />
            <mesh
              name="Object_413"
              castShadow
              receiveShadow
              geometry={nodes.Object_413.geometry}
              material={materials.Emmision}
            />
          </group>
          <group name="Sphere008_191" position={[0, -0.116, 0.557]}>
            <mesh
              name="Object_415"
              castShadow
              receiveShadow
              geometry={nodes.Object_415.geometry}
              material={materials.Shop}
            />
            <mesh
              name="Object_416"
              castShadow
              receiveShadow
              geometry={nodes.Object_416.geometry}
              material={materials.Emmision}
            />
          </group>
          <group name="Sphere009_192" position={[0, -0.21, 0.386]}>
            <mesh
              name="Object_418"
              castShadow
              receiveShadow
              geometry={nodes.Object_418.geometry}
              material={materials.Shop}
            />
            <mesh
              name="Object_419"
              castShadow
              receiveShadow
              geometry={nodes.Object_419.geometry}
              material={materials.Emmision}
            />
          </group>
          <group name="Sphere010_193" position={[0, -0.173, 0.153]}>
            <mesh
              name="Object_421"
              castShadow
              receiveShadow
              geometry={nodes.Object_421.geometry}
              material={materials.Shop}
            />
            <mesh
              name="Object_422"
              castShadow
              receiveShadow
              geometry={nodes.Object_422.geometry}
              material={materials.Emmision}
            />
          </group>
        </group>
        <group name="Plane017_201" position={[0.007, 0.764, 0.198]} rotation={[0, Math.PI / 2, 0]}>
          <mesh
            name="Object_424"
            castShadow
            receiveShadow
            geometry={nodes.Object_424.geometry}
            material={materials.tbjr_material}
          />
          <mesh
            name="Object_425"
            castShadow
            receiveShadow
            geometry={nodes.Object_425.geometry}
            material={materials.material_0}
          />
          <mesh
            name="Object_427"
            castShadow
            receiveShadow
            geometry={nodes.Object_427.geometry}
            material={materials.tbjr_material}
            position={[-0.224, 0.029, -0.03]}
          />
          <mesh
            name="Object_429"
            castShadow
            receiveShadow
            geometry={nodes.Object_429.geometry}
            material={materials.tbjr_material}
            position={[-0.224, 0.029, 0.032]}
          />
          <mesh
            name="Object_431"
            castShadow
            receiveShadow
            geometry={nodes.Object_431.geometry}
            material={materials.tbjr_material}
            position={[-0.159, 0.029, -0.03]}
          />
          <mesh
            name="Object_433"
            castShadow
            receiveShadow
            geometry={nodes.Object_433.geometry}
            material={materials.tbjr_material}
            position={[-0.159, 0.029, 0.032]}
          />
          <mesh
            name="Object_435"
            castShadow
            receiveShadow
            geometry={nodes.Object_435.geometry}
            material={materials.tbjr_material}
            position={[-0.093, 0.029, -0.03]}
          />
          <mesh
            name="Object_437"
            castShadow
            receiveShadow
            geometry={nodes.Object_437.geometry}
            material={materials.tbjr_material}
            position={[-0.093, 0.029, 0.032]}
          />
        </group>
        <mesh
          name="Object_97"
          castShadow
          receiveShadow
          geometry={nodes.Object_97.geometry}
          material={materials.gradient_glossy}
          position={[0.8, 0.642, -0.029]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="Object_99"
          castShadow
          receiveShadow
          geometry={nodes.Object_99.geometry}
          material={materials.tbjr_material}
          position={[0.592, 0.652, -0.609]}
          rotation={[0, -0.336, 0.168]}
        />
        <mesh
          name="Object_143"
          castShadow
          receiveShadow
          geometry={nodes.Object_143.geometry}
          material={materials.tbjr_material}
          position={[-0.29, 0.171, -0.532]}
          rotation={[0, 1.187, 0]}
        />
        <mesh
          name="Object_145"
          castShadow
          receiveShadow
          geometry={nodes.Object_145.geometry}
          material={materials.tbjr_material}
          position={[-0.111, 1.495, -0.807]}
        />
        <mesh
          name="Object_147"
          castShadow
          receiveShadow
          geometry={nodes.Object_147.geometry}
          material={materials.tbjr_material}
          position={[0.763, 0.171, 0.859]}
          rotation={[0, 1.187, 0]}
        />
        <mesh
          name="Object_201"
          castShadow
          receiveShadow
          geometry={nodes.Object_201.geometry}
          material={materials.tbjr_material}
          position={[0.307, 0.755, -0.698]}
          rotation={[-Math.PI, 1.405, -Math.PI]}
        />
      </group>
    </group>
  )
}

useGLTF.preload(MODEL_URL);
