/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AK STUDIO (https://sketchfab.com/inven2000)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coffee-cup-992750b0df674378989fa915b0688ce1
Title: Coffee Cup
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import cup from '../public/models/coffee_cup.glb';
import gsap from 'gsap';
import { useGSAP } from '@gsap/react';



type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial: THREE.Mesh
  }
  materials: {
    DefaultMaterial: THREE.MeshStandardMaterial
  }
}

export function CoffeeCup(props: JSX.IntrinsicElements['group']) {
  const targetRef = useRef();
  const { nodes, materials } = useGLTF(cup) as GLTFResult
   /* useGSAP( () => {
        gsap.to(targetRef.current.position, {
        y: targetRef.current.position.y + 0.5,
        duration: 1.5,
        repeat: -1,
        yoyo: true,
    
  });*/

  return (
    <group {...props} dispose={null} >
      <group name="Sketchfab_Scene" >
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.099}>
          <group name="Collada_visual_scene_group" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Coffee_Cup">
              <mesh
                name="defaultMaterial"
                castShadow
                receiveShadow
                geometry={nodes.defaultMaterial.geometry}
                material={materials.DefaultMaterial}
                ref={targetRef.current}
              />
              
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(cup)
